// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ReceiptFlow.Infrastructure.Persistence;

#nullable disable

namespace ReceiptFlow.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260720124927_AddManualSupportFoundation")]
    partial class AddManualSupportFoundation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.InboxState", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("Consumed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ConsumerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Delivered")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("LastSequenceNumber")
                        .HasColumnType("bigint");

                    b.Property<Guid>("LockId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<int>("ReceiveCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Received")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("Delivered");

                    b.ToTable("InboxState");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxMessage", b =>
                {
                    b.Property<long>("SequenceNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("SequenceNumber"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid?>("ConversationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<string>("DestinationAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("EnqueueTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FaultAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Headers")
                        .HasColumnType("text");

                    b.Property<Guid?>("InboxConsumerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("InboxMessageId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("InitiatorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("OutboxId")
                        .HasColumnType("uuid");

                    b.Property<string>("Properties")
                        .HasColumnType("text");

                    b.Property<Guid?>("RequestId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResponseAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("SentTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SourceAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("SequenceNumber");

                    b.HasIndex("EnqueueTime");

                    b.HasIndex("ExpirationTime");

                    b.HasIndex("OutboxId", "SequenceNumber")
                        .IsUnique();

                    b.HasIndex("InboxMessageId", "InboxConsumerId", "SequenceNumber")
                        .IsUnique();

                    b.ToTable("OutboxMessage");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxState", b =>
                {
                    b.Property<Guid>("OutboxId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BusName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Delivered")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("LastSequenceNumber")
                        .HasColumnType("bigint");

                    b.Property<Guid>("LockId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.HasKey("OutboxId");

                    b.HasIndex("Created");

                    b.HasIndex("BusName", "Created");

                    b.ToTable("OutboxState");
                });

            modelBuilder.Entity("ReceiptFlow.Domain.Entities.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("document_type");

                    b.Property<string>("ExtractedTextStorageKey")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("extracted_text_storage_key");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("failure_reason");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("original_file_name");

                    b.Property<string>("OwnerUserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("owner_user_id");

                    b.Property<int?>("PageCount")
                        .HasColumnType("integer")
                        .HasColumnName("page_count");

                    b.Property<DateTimeOffset?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at_utc");

                    b.Property<DateTimeOffset?>("ProcessingStartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processing_started_at_utc");

                    b.Property<string>("ProcessingStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("processing_status");

                    b.Property<Guid?>("ReceiptId")
                        .HasColumnType("uuid")
                        .HasColumnName("receipt_id");

                    b.Property<string>("Sha256Hash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("sha256_hash");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("storage_key");

                    b.HasKey("Id");

                    b.HasAlternateKey("Id", "OwnerUserId")
                        .HasName("ak_documents_id_owner_user_id");

                    b.HasIndex("ReceiptId");

                    b.HasIndex("StorageKey")
                        .IsUnique()
                        .HasDatabaseName("ux_documents_storage_key");

                    b.HasIndex("OwnerUserId", "ProcessingStatus")
                        .HasDatabaseName("ix_documents_owner_user_id_processing_status");

                    b.HasIndex("OwnerUserId", "Sha256Hash")
                        .HasDatabaseName("ix_documents_owner_user_id_sha256_hash");

                    b.ToTable("documents", null, t =>
                        {
                            t.HasCheckConstraint("ck_documents_product_manual_not_receipt", "NOT (receipt_id IS NOT NULL AND document_type = 'ProductManual')");
                        });
                });

            modelBuilder.Entity("ReceiptFlow.Domain.Entities.DocumentExtraction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category");

                    b.Property<string>("Currency")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<DateTimeOffset>("ExtractedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("extracted_at_utc");

                    b.Property<string>("MerchantName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("merchant_name");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("model_id");

                    b.Property<decimal?>("OverallConfidence")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)")
                        .HasColumnName("overall_confidence");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("provider");

                    b.Property<string>("RawText")
                        .HasColumnType("text")
                        .HasColumnName("raw_text");

                    b.Property<string>("StructuredDataJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("structured_data_json");

                    b.Property<decimal?>("Subtotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("subtotal");

                    b.Property<decimal?>("Tax")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("tax");

                    b.Property<decimal?>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total");

                    b.Property<DateTimeOffset?>("TransactionDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("transaction_date");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId")
                        .IsUnique()
                        .HasDatabaseName("ux_document_extractions_document_id");

                    b.ToTable("document_extractions", (string)null);
                });

            modelBuilder.Entity("ReceiptFlow.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("manufacturer");

                    b.Property<string>("ModelNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("model_number");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedManufacturer")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("normalized_manufacturer");

                    b.Property<string>("NormalizedModelNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("normalized_model_number");

                    b.Property<string>("OwnerUserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("owner_user_id");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasAlternateKey("Id", "OwnerUserId")
                        .HasName("ak_products_id_owner_user_id");

                    b.HasIndex("OwnerUserId")
                        .HasDatabaseName("ix_products_owner_user_id");

                    b.HasIndex("OwnerUserId", "NormalizedManufacturer", "NormalizedModelNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_products_owner_manufacturer_model")
                        .HasFilter("normalized_model_number IS NOT NULL");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("ReceiptFlow.Domain.Entities.ProductManual", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ConfirmedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmed_at_utc");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<string>("LifecycleStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("lifecycle_status");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("locale");

                    b.Property<string>("ManualKind")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("manual_kind");

                    b.Property<string>("OwnerUserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("owner_user_id");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<DateTimeOffset?>("SupersededAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("superseded_at_utc");

                    b.Property<Guid?>("SupersedesProductManualId")
                        .HasColumnType("uuid")
                        .HasColumnName("supersedes_product_manual_id");

                    b.Property<string>("VersionLabel")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("version_label");

                    b.Property<int?>("WarrantyDurationMonths")
                        .HasColumnType("integer")
                        .HasColumnName("warranty_duration_months");

                    b.HasKey("Id");

                    b.HasAlternateKey("Id", "ProductId", "OwnerUserId")
                        .HasName("ak_product_manuals_id_product_id_owner_user_id");

                    b.HasIndex("DocumentId")
                        .IsUnique()
                        .HasDatabaseName("ux_product_manuals_document_id");

                    b.HasIndex("DocumentId", "OwnerUserId")
                        .IsUnique();

                    b.HasIndex("ProductId", "OwnerUserId");

                    b.HasIndex("SupersedesProductManualId", "ProductId", "OwnerUserId");

                    b.HasIndex("OwnerUserId", "ProductId", "ManualKind", "Locale")
                        .IsUnique()
                        .HasDatabaseName("ux_product_manuals_active_family")
                        .HasFilter("lifecycle_status = 'Active'");

                    b.ToTable("product_manuals", null, t =>
                        {
                            t.HasCheckConstraint("ck_product_manuals_warranty_duration", "warranty_duration_months IS NULL OR (warranty_duration_months >= 1 AND warranty_duration_months <= 1200)");
                        });
                });

            modelBuilder.Entity("ReceiptFlow.Domain.Entities.Purchase", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("OwnerUserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("owner_user_id");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("quantity");

                    b.Property<Guid>("ReceiptId")
                        .HasColumnType("uuid")
                        .HasColumnName("receipt_id");

                    b.Property<Guid?>("ReceiptLineItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("receipt_line_item_id");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<int?>("WarrantyDurationMonthsSnapshot")
                        .HasColumnType("integer")
                        .HasColumnName("warranty_duration_months_snapshot");

                    b.Property<Guid?>("WarrantySourceProductManualId")
                        .HasColumnType("uuid")
                        .HasColumnName("warranty_source_product_manual_id");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId")
                        .HasDatabaseName("ix_purchases_owner_user_id");

                    b.HasIndex("ReceiptLineItemId");

                    b.HasIndex("ProductId", "OwnerUserId");

                    b.HasIndex("ReceiptId", "OwnerUserId");

                    b.HasIndex("OwnerUserId", "ProductId", "ReceiptId")
                        .IsUnique()
                        .HasDatabaseName("ux_purchases_product_receipt_without_line_item")
                        .HasFilter("receipt_line_item_id IS NULL");

                    b.HasIndex("WarrantySourceProductManualId", "ProductId", "OwnerUserId");

                    b.HasIndex("OwnerUserId", "ProductId", "ReceiptId", "ReceiptLineItemId")
                        .IsUnique()
                        .HasDatabaseName("ux_purchases_product_receipt_line_item")
                        .HasFilter("receipt_line_item_id IS NOT NULL");

                    b.ToTable("purchases", null, t =>
                        {
                            t.HasCheckConstraint("ck_purchases_quantity", "quantity > 0");

                            t.HasCheckConstraint("ck_purchases_warranty_source", "(warranty_source_product_manual_id IS NULL AND warranty_duration_months_snapshot IS NULL) OR (warranty_source_product_manual_id IS NOT NULL AND warranty_duration_months_snapshot IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("ReceiptFlow.Domain.Entities.Receipt", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Currency")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<string>("LifecycleStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("lifecycle_status");

                    b.Property<string>("MerchantName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("merchant_name");

                    b.Property<string>("OwnerUserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("owner_user_id");

                    b.Property<DateTimeOffset?>("PurchaseDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("purchase_date");

                    b.Property<decimal?>("SubtotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("subtotal_amount");

                    b.Property<decimal?>("TaxAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("tax_amount");

                    b.Property<decimal?>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total_amount");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasAlternateKey("Id", "OwnerUserId")
                        .HasName("ak_receipts_id_owner_user_id");

                    b.HasIndex("OwnerUserId")
                        .HasDatabaseName("ix_receipts_owner_user_id");

                    b.HasIndex("OwnerUserId", "LifecycleStatus")
                        .HasDatabaseName("ix_receipts_owner_user_id_lifecycle_status");

                    b.HasIndex("OwnerUserId", "PurchaseDate")
                        .HasDatabaseName("ix_receipts_owner_user_id_purchase_date");

                    b.ToTable("receipts", (string)null);
                });

            modelBuilder.Entity("ReceiptFlow.Domain.Entities.ReceiptLineItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<decimal>("LineTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("line_total");

                    b.Property<string>("ProductCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("product_code");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("quantity");

                    b.Property<Guid>("ReceiptId")
                        .HasColumnType("uuid")
                        .HasColumnName("receipt_id");

                    b.Property<decimal?>("TaxAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("tax_amount");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("unit_price");

                    b.HasKey("Id");

                    b.HasIndex("ReceiptId", "DisplayOrder")
                        .IsUnique()
                        .HasDatabaseName("ux_receipt_line_items_receipt_id_display_order");

                    b.ToTable("receipt_line_items", (string)null);
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxMessage", b =>
                {
                    b.HasOne("MassTransit.EntityFrameworkCoreIntegration.OutboxState", null)
                        .WithMany()
                        .HasForeignKey("OutboxId");

                    b.HasOne("MassTransit.EntityFrameworkCoreIntegration.InboxState", null)
                        .WithMany()
                        .HasForeignKey("InboxMessageId", "InboxConsumerId")
                        .HasPrincipalKey("MessageId", "ConsumerId");
                });

            modelBuilder.Entity("ReceiptFlow.Domain.Entities.Document", b =>
                {
                    b.HasOne("ReceiptFlow.Domain.Entities.Receipt", "Receipt")
                        .WithMany("Documents")
                        .HasForeignKey("ReceiptId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Receipt");
                });

            modelBuilder.Entity("ReceiptFlow.Domain.Entities.DocumentExtraction", b =>
                {
                    b.HasOne("ReceiptFlow.Domain.Entities.Document", "Document")
                        .WithOne("Extraction")
                        .HasForeignKey("ReceiptFlow.Domain.Entities.DocumentExtraction", "DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("ReceiptFlow.Domain.Entities.ProductManual", b =>
                {
                    b.HasOne("ReceiptFlow.Domain.Entities.Document", "Document")
                        .WithOne("ProductManual")
                        .HasForeignKey("ReceiptFlow.Domain.Entities.ProductManual", "DocumentId", "OwnerUserId")
                        .HasPrincipalKey("ReceiptFlow.Domain.Entities.Document", "Id", "OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ReceiptFlow.Domain.Entities.Product", "Product")
                        .WithMany("Manuals")
                        .HasForeignKey("ProductId", "OwnerUserId")
                        .HasPrincipalKey("Id", "OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ReceiptFlow.Domain.Entities.ProductManual", "SupersedesProductManual")
                        .WithMany()
                        .HasForeignKey("SupersedesProductManualId", "ProductId", "OwnerUserId")
                        .HasPrincipalKey("Id", "ProductId", "OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Document");

                    b.Navigation("Product");

                    b.Navigation("SupersedesProductManual");
                });

            modelBuilder.Entity("ReceiptFlow.Domain.Entities.Purchase", b =>
                {
                    b.HasOne("ReceiptFlow.Domain.Entities.ReceiptLineItem", "ReceiptLineItem")
                        .WithMany()
                        .HasForeignKey("ReceiptLineItemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ReceiptFlow.Domain.Entities.Product", "Product")
                        .WithMany("Purchases")
                        .HasForeignKey("ProductId", "OwnerUserId")
                        .HasPrincipalKey("Id", "OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ReceiptFlow.Domain.Entities.Receipt", "Receipt")
                        .WithMany()
                        .HasForeignKey("ReceiptId", "OwnerUserId")
                        .HasPrincipalKey("Id", "OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ReceiptFlow.Domain.Entities.ProductManual", "WarrantySourceProductManual")
                        .WithMany()
                        .HasForeignKey("WarrantySourceProductManualId", "ProductId", "OwnerUserId")
                        .HasPrincipalKey("Id", "ProductId", "OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Product");

                    b.Navigation("Receipt");

                    b.Navigation("ReceiptLineItem");

                    b.Navigation("WarrantySourceProductManual");
                });

            modelBuilder.Entity("ReceiptFlow.Domain.Entities.ReceiptLineItem", b =>
                {
                    b.HasOne("ReceiptFlow.Domain.Entities.Receipt", "Receipt")
                        .WithMany("LineItems")
                        .HasForeignKey("ReceiptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Receipt");
                });

            modelBuilder.Entity("ReceiptFlow.Domain.Entities.Document", b =>
                {
                    b.Navigation("Extraction");

                    b.Navigation("ProductManual");
                });

            modelBuilder.Entity("ReceiptFlow.Domain.Entities.Product", b =>
                {
                    b.Navigation("Manuals");

                    b.Navigation("Purchases");
                });

            modelBuilder.Entity("ReceiptFlow.Domain.Entities.Receipt", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("LineItems");
                });
#pragma warning restore 612, 618
        }
    }
}
